MaxWitnessSignatures: 5

Witnesses:
  - can-I-get-a-witness+b97a1e56+AZkpOlwZwR+wwasAENZwIa98ufmWmzlq0Tx0XN7voU6X
  - witness-over-here+29c4e8f4+AUbwUCBUM2sDdHeiKUrp6LnMErE7GEz0iH+0WbgbJZxx
  - wolsey-bank-alfred+0336ecb0+AVcofP6JyFkxhQ+/FK7omBtGLVS22tGC6fH+zvK5WrIx

Logs:
  - ID: serverless-test
    PublicKey: github.com/AlCutter/serverless-test/log+28035191+AVtQ/9lW+g90rQY3+pODJvMQ8X/tTvh/EuvCDLSmUk4S
    Origin: github.com/AlCutter/serverless-test/log
  - ID: armory-drive-log
    PublicKey: armory-drive-log+10146603+Af48wFx6DzAklbp4iZaMFGXoEBZxUwEMQMID4lovBq6X
    Origin: Armory Drive Prod 1
  - ID: armory-drive-log-2
    PublicKey: armory-drive-log+16541b8f+AYDPmG5pQp4Bgu0a1mr5uDZ196+t8lIVIfWQSPWmP+Jv
    Origin: Armory Drive Prod 2

