on:
  pull_request:
    branches:
      - master

jobs:
  leaf_validator_job:
    runs-on: ubuntu-latest
    name: Validate pending leaves
    steps:
    - uses: actions/checkout@v2
    - name: Leaf validator step
      id: leaf_validator
      uses: AlCutter/trillian-examples/serverless/deploy/github/leaf_validator@serverless_leaf_validator
      with:
        log_dir: './log'