name: Serverless PR
on:
  pull_request_target:
    branches:
      - master

env:
  LOG_ROOT: "log"
  DISTRIBUTOR_ROOT: "distributor"

jobs:
  changes:
    runs-on: ubuntu-latest
    name: Serverless PR handler
    outputs:
      # Add extra outputs here to match any additions to the matched patterns in the filter step below.
      distributor: ${{ steps.filter.outputs.distributor }}
      log: ${{ steps.filter.outputs.log }}
      pending: ${{ steps.filter.outputs.pending }}
    steps:
      - name: Check for log structure PRs
        id: filter
        uses: dorny/paths-filter@v2
        with:
          list-files: shell
          filters: |
            distributor:
              - added: '${{ env.DISTRIBUTOR_ROOT }}/logs/**'
            log:
              - '${{ env.LOG_ROOT }}/**'
            pending:
              - added: '${{ env.LOG_ROOT }}/leaves/pending/*'

      - name: Detect log structure changes
        if: steps.filter.outputs.log == 'true' && steps.filter.outputs.pending == 'false'
        run: |
          for i in ${{ steps.filter.outputs.log_files }}; do
            echo "::error file=${i}::Modified protected log structure"
          done
          exit 1

      - name: Detect combined PRs
        if: steps.filter.outputs.pending == 'true' && steps.filter.outputs.distributor == 'true'
        run: |
          for i in ${{ steps.filter.outputs.log_files }} ${{ steps.filter.outputs.distributor_files }}; do
            echo "::error file=${i}::PR contains new leaves and witnessed checkpoints, please split into multiple PRs"
          done
          exit 1


# Run this job only when we've detected pending leaf additions
  leaf_validator:
    needs: changes
    if: ${{ needs.changes.outputs.pending == 'true' }}
    runs-on: ubuntu-latest
    name: Validate pending leaves
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: Add Leaf
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: Leaf validator step
        id: leaf_validator
        uses: google/trillian-examples/serverless/deploy/github/log/leaf_validator@HEAD
        with:
          log_dir: '${{ env.LOG_ROOT }}'

# Run this job only when we've detected a distributor checkpoint PR
  distributor_validator:
    needs: changes
    if: ${{ needs.changes.outputs.distributor == 'true' }}
    runs-on: ubuntu-latest
    name: Handle distributor PR
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: Witness
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: Combine witness signatures (dry run)
        id: combine_witness_signatures_dry_run
        uses: AlCutter/trillian-examples/serverless/deploy/github/distributor/combine_witness_signatures@serverless_distributor
        with:
            distributor_dir: './distributor'
            config: './distributor/config.json'
            dry_run: true
