name: Serverless PR
on:
  pull_request:
    branches:
      - master

env:
  LOG_ROOT: "log"
  DISTRIBUTOR_ROOT: "distributor"

jobs:
  changes:
    runs-on: ubuntu-latest
    name: Serverless PR handler
    outputs:
      # Add extra outputs here to match any additions to the matched patterns in the filter step below.
      distributor_incoming: ${{ steps.filter.outputs.distributor_incoming }}
      log_pending: ${{ steps.filter.outputs.log_pending }}
    steps:
      - name: Check for log structure PRs
        id: filter
        uses: dorny/paths-filter@v2
        with:
          list-files: shell
          filters: |
            distributor_incoming:
              - added: '${{ env.DISTRIBUTOR_ROOT }}/logs/*/incoming/*'
            distributor_private:
              - '${{ env.DISTRIBUTOR_ROOT }}!(/logs/*/incoming/*)'
            log_pending:
              - added: '${{ env.LOG_ROOT }}/leaves/pending/*'
            log_private:
              - '${{ env.LOG_ROOT }}/!(leaves/pending/*)'

      - name: Detect log structure changes
        if: steps.filter.outputs.log_private == 'true'
        run: |
          for i in ${{ steps.filter.outputs.log_private_files }}; do
            echo "::error file=${i}::Modified protected log structure"
          done
          exit 1

      - name: Detect distributor structure changes
        if: steps.filter.outputs.distributor_private == 'true'
        run: |
          for i in ${{ steps.filter.outputs.distributor_private_files }}; do
            echo "::error file=${i}::Modified protected distributor structure"
          done
          exit 1

      - name: Detect combined PRs
        if: steps.filter.outputs.log_pending == 'true' && steps.filter.outputs.distributor_incoming == 'true'
        run: |
          for i in ${{ steps.filter.outputs.log_pending_files }} ${{ steps.filter.outputs.distributor_pending_files }}; do
            echo "::error file=${i}::PR contains new leaves and witnessed checkpoints, please split into multiple PRs"
          done
          exit 1


# Run this job only when we've detected pending leaf additions
  leaf_validator:
    needs: changes
    if: ${{ needs.changes.outputs.log_pending == 'true' }}
    runs-on: ubuntu-latest
    name: Validate pending leaves
    steps:
            #      - uses: actions-ecosystem/action-add-labels@v1
            #        with:
            #          labels: Add Leaf
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: Leaf validator step
        id: leaf_validator
        uses: google/trillian-examples/serverless/deploy/github/log/leaf_validator@HEAD
        with:
          log_dir: '${{ env.LOG_ROOT }}'

# Run this job only when we've detected a distributor checkpoint PR
  distributor_validator:
    needs: changes
    if: ${{ needs.changes.outputs.distributor_incoming == 'true' }}
    runs-on: ubuntu-latest
    name: Handle distributor PR
    steps:
            #      - uses: actions-ecosystem/action-add-labels@v1
            #        with:
            #          labels: Witness
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: Combine witness signatures (dry run)
        id: combine_witness_signatures_dry_run
        uses: google/trillian-examples/serverless/deploy/github/distributor/combine_witness_signatures@HEAD
        with:
            distributor_dir: './distributor'
            config: './distributor/config.yaml'
            dry_run: true
      # Store PR number so we can update from a more priviledged workflow.
      - id: save_metadata
        name: Save PR number
        run: |
          D=$(mktemp -d)/pr_metadata
          mkdir -p ${D}
          echo ${{ github.event.number }} > ${D}/NR
          echo "::set-output name=metadata_dir::${D}"
      - uses: actions/upload-artifact@v2
        with:
          name: pr_metadata
          path: ${{ steps.save_metadata.outputs.metadata_dir }}
