on:
  pull_request:
    branches:
      - master

jobs:
  serverless_pr:
    runs-on: ubuntu-latest
    name: Serverless PR handler
    steps:
      - name: Check for log structure PRs
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            log:
              - 'log/**'
            pending:
              - added: 'log/leaves/pending/*'

      - name: Detect log structure changes
        if: steps.changes.outputs.log == 'true' && steps.changes.outputs.pending == 'false'
        run: |
          echo "::error:PR modifies protected log structure - ensure additions are placed in the .../leaves/pending directory"

# Run this job only when we've detected pending leaf additions
  leaf_validator_job:
    needs: changes
    if: ${{ needs.changes.outputs.pending == 'true' }}
    runs-on: ubuntu-latest
    name: Validate pending leaves
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Leaf validator step
      id: leaf_validator
      uses: google/trillian-examples/serverless/deploy/github/leaf_validator@HEAD
      with:
        log_dir: './log'

