on:
  pull_request:
    branches:
      - master

jobs:
  serverless_pr:
    runs-on: ubuntu-latest
    name: Serverless PR handler
    steps:
      - uses: actions/checkout@v2

      - name: Check for log structure PRs
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            log:
              - '^log/**'
            pending:
              - added: '^log/leaves/pending/*$'

      - name: Detect log structure changes
        if: steps.changes.outputs.log == 'true' && steps.changes.outputs.pending == 'false'
        run: |
          echo "::error:PR modifies log structure"

      - name: Handle leaf PR
        if: steps.changes.outputs.pending == 'true'
        run: |
          echo "::warning:Will handle leaf PR"

