on:
  pull_request:
    branches:
      - master

jobs:
  leaf_validator_job:
    runs-on: ubuntu-latest
    name: Handle witness PR
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Validate witness PR
      id: validate_witness_pr
      uses: google/trillian-examples/serverless/deploy/github/witness_pr@master
      with:
        log_dir: './log'
        witness_key_files: 'witnesskeys/*pub'
        log_public_key: 'github.com/AlCutter/serverless-test/log+28035191+AVtQ/9lW+g90rQY3+pODJvMQ8X/tTvh/EuvCDLSmUk4S'

